version: '3.7'

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: ${PROMETHEUS}
        hostname: ${PROMETHEUS}
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/data:/prometheus
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=200h'
            - '--web.enable-admin-api'
            - '--web.enable-lifecycle'
    grafana:
        image: grafana/grafana:latest
        container_name: ${GRAFANA}
        hostname: ${GRAFANA}
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        env_file:
            - ./grafana/config
        ports:
            - "3000:3000"
